// Copyright (c) 2023 The TQUIC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! A QUIC endpoint.

#![allow(unused_variables)]

mod connection_routes;
mod connection_table;
mod packet_buffer;
mod packet_queue;

use std::cell::RefCell;
use std::cmp;
use std::net::SocketAddr;
use std::rc::Rc;
use std::time::Duration;
use std::time::Instant;

use log::*;
use ring::hmac;
use rustc_hash::FxHashSet;

use crate::connection::Connection;
use crate::error::Error;
use crate::packet;
use crate::packet::PacketHeader;
use crate::packet::PacketType;
use crate::timer_queue::TimerQueue;
use crate::token::AddressToken;
use crate::token::AddressTokenType::*;
use crate::token::ResetToken;
use crate::ConnectionId;
use crate::ConnectionIdGenerator;
use crate::ConnectionQueues;
use crate::Event;
use crate::FourTuple;
use crate::PacketInfo;
use crate::PacketSendHandler;
use crate::Result;
use crate::TransportHandler;

use connection_routes::ConnectionRoutes;
use connection_table::ConnectionTable;
use packet_buffer::PacketBuffer;
use packet_queue::PacketQueue;

#[cfg(test)]
mod tests;

/// Endpoint is an entity that can participate in a QUIC connection by
/// generating, receiving, and processing QUIC packets.
///
/// There are two types of endpoints in QUIC: client and server. Endpoint may
/// maintain one or more QUIC connections.  Endpoint provides a high level API
/// to use the QUIC library.
pub struct Endpoint {
    /// Whether this is a server endpoint.
    is_server: bool,

    /// QUIC Configuration
    config: Box<crate::Config>,

    /// All connections on the endpoint.
    conns: ConnectionTable,

    /// Used for matching incoming packets to connections.
    routes: ConnectionRoutes,

    /// Connections ordered by expiration time.
    timers: TimerQueue,

    /// Various connection queues.
    queues: Rc<RefCell<ConnectionQueues>>,

    /// Connection ID Generator.
    cid_gen: Box<dyn ConnectionIdGenerator>,

    /// Used to communicate with the application code.
    handler: Box<dyn TransportHandler>,

    /// Used to send packet out.
    sender: Rc<dyn PacketSendHandler>,

    /// Buffer for ZeroRTT packets that arrive before Initial packets due to
    /// potential misordering or loss of Initial packets.
    buffer: PacketBuffer,

    /// Packets generated by the endpoint.
    packets: PacketQueue,

    /// The endpoint is shutdown.
    closed: bool,

    /// The unique trace id for the endpoint
    trace_id: String,
}

impl Endpoint {
    /// Create a QUIC endpoint.
    pub fn new(
        config: Box<crate::Config>,
        is_server: bool,
        handler: Box<dyn TransportHandler>,
        sender: Rc<dyn PacketSendHandler>,
    ) -> Self {
        let cid_gen = Box::new(crate::RandomConnectionIdGenerator {
            cid_len: config.cid_len,
        });
        let trace_id = if is_server { "SERVER" } else { "CLIENT" };
        let buffer = PacketBuffer::new(config.zerortt_buffer_size);
        let packets = PacketQueue::new(config.send_batch_size);

        Self {
            is_server,
            config,
            conns: ConnectionTable::new(),
            routes: ConnectionRoutes::new(),
            timers: TimerQueue::new(),
            queues: Rc::new(RefCell::new(ConnectionQueues::new())),
            cid_gen,
            handler,
            sender,
            buffer,
            packets,
            closed: false,
            trace_id: trace_id.to_string(),
        }
    }

    /// Create a client connection.
    /// Note: The `config` specific to the endpoint or server is irrelevant
    /// and will be disregarded.
    ///
    /// The caller should call `process_connections()` after one or more
    /// connect().
    pub fn connect(
        &mut self,
        local: SocketAddr,
        remote: SocketAddr,
        server_name: Option<&str>,
        session: Option<&[u8]>,
        token: Option<&[u8]>,
        config: Option<&crate::Config>,
    ) -> Result<u64> {
        if self.is_server {
            return Err(Error::InvalidOperation("not a client".into()));
        }
        if self.closed {
            return Err(Error::InvalidOperation("already closed".into()));
        }

        let scid = self.cid_gen.generate();
        let config = config.unwrap_or(&self.config);
        let conn = Connection::new_client(&scid, local, remote, server_name, config)?;
        let idx = self.conns.insert(conn);
        self.init_client_conn(idx, session, token)?;
        self.add_client_route(&scid, idx, local, remote);

        Ok(idx)
    }

    /// Initialize a newly-created client connection.
    fn init_client_conn(
        &mut self,
        idx: u64,
        session: Option<&[u8]>,
        token: Option<&[u8]>,
    ) -> Result<()> {
        if let Some(conn) = self.conns.get_mut(idx) {
            conn.set_index(idx);
            conn.set_queues(self.queues.clone());
            if let Some(session) = session {
                conn.set_session(session)?;
            }
            if let Some(token) = token {
                conn.set_token(token.to_vec())?;
            }
            conn.start_handshake()?;
            self.handler.on_conn_created(conn);
            conn.mark_tickable(true);
        }
        Ok(())
    }

    /// Add routing entry for a client connection.
    fn add_client_route(
        &mut self,
        scid: &ConnectionId,
        idx: u64,
        local: SocketAddr,
        remote: SocketAddr,
    ) {
        if !scid.is_empty() {
            self.routes.insert_with_cid(*scid, idx);
        } else {
            self.routes
                .insert_with_addr(FourTuple { local, remote }, idx);
        }
    }

    /// Process an incoming UDP datagram.
    ///
    /// Incoming packets are classified on receipt. Packets can either be
    /// associated with an existing connection or for servers potentially create
    /// a new connection.
    /// See RFC 9000 Section 5.2 Matching Packets to Connections.
    pub fn recv(&mut self, buf: &mut [u8], info: &PacketInfo) -> Result<()> {
        trace!(
            "{} recv packet {} bytes {:?}",
            &self.trace_id,
            buf.len(),
            info
        );

        let cid_len = self.cid_gen.cid_len();
        let (mut hdr, _) = PacketHeader::from_bytes(buf, cid_len)?;
        let (local, remote) = (info.dst, info.src);

        // Try to delivery the datagram to the target connection.
        if let (Some(c), reset) = self.routes.find(&hdr.dcid, buf, info) {
            return self.recv_existing_conn(*c, reset, buf, info);
        }

        // Drop the datagram for unrecognized connection for client
        if !self.is_server {
            return self.recv_unknown_client(&hdr, buf.len(), local, remote);
        }

        // Try to create a new connection for server
        if hdr.pkt_type == PacketType::Initial && !self.closed {
            return self.recv_server_initial(&mut hdr, buf, info, local, remote);
        }

        // Try to buffer ZeroRTT packets for the unknown connection on the server
        if hdr.pkt_type == PacketType::ZeroRTT && !self.closed {
            self.buffer.add(hdr.dcid, buf.to_vec(), *info);
        }

        // Send the Stateless Reset packet for the unknown connection
        if hdr.pkt_type == PacketType::OneRTT && !hdr.dcid.is_empty() && self.config.stateless_reset
        {
            self.send_stateless_reset(buf.len(), &hdr.dcid, local, remote)?;
            return Ok(());
        }

        // Ignore non-initial packet for unknown connection
        Ok(())
    }

    /// Deliver a datagram to an existing connection.
    fn recv_existing_conn(
        &mut self,
        idx: u64,
        reset: bool,
        buf: &mut [u8],
        info: &PacketInfo,
    ) -> Result<()> {
        if let Some(conn) = self.conns.get_mut(idx) {
            conn.mark_tickable(true);
            if reset && self.config.stateless_reset {
                trace!(
                    "{} connection {:?} got stateless reset from {:?}",
                    &self.trace_id,
                    conn.trace_id(),
                    info
                );
                conn.reset();
                return Ok(());
            }
            conn.recv(buf, info).map(|_| ())?;
        }
        Ok(())
    }

    /// Handle a datagram for an unknown connection on client side.
    fn recv_unknown_client(
        &mut self,
        hdr: &PacketHeader,
        pkt_len: usize,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        if self.config.stateless_reset {
            self.send_stateless_reset(pkt_len, &hdr.dcid, local, remote)?;
        }
        Ok(())
    }

    /// Handle an Initial packet on the server to create a new connection.
    fn recv_server_initial(
        &mut self,
        hdr: &mut PacketHeader,
        buf: &mut [u8],
        info: &PacketInfo,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        if self.conns.len() >= self.config.max_concurrent_conns as usize {
            return Ok(());
        }
        if !crate::version_is_supported(hdr.version) {
            return self.send_version_negotiation(hdr, local, remote);
        }

        let token = self.validate_initial_token(hdr, local, remote)?;
        let odcid = match token {
            Some(ref token) => token.odcid.unwrap(), // always success
            None => hdr.dcid,
        };

        let idx = self.create_server_conn(hdr, token.as_ref(), local, remote)?;
        self.deliver_initial_to_conn(idx, hdr, buf, info)?;

        Ok(())
    }

    /// Validate the address token in an Initial packet.
    fn validate_initial_token(
        &mut self,
        hdr: &mut PacketHeader,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<Option<AddressToken>> {
        if let Some(ref mut token) = hdr.token {
            match self.validate_address_token(token, &remote, &hdr.dcid) {
                Ok(token) => Ok(Some(token)),
                Err(_) => match AddressToken::token_type(token) {
                    Ok(RetryToken) => Err(Error::InvalidToken),
                    _ => {
                        self.send_retry(hdr, local, remote)?;
                        Err(Error::Done)
                    }
                },
            }
        } else if self.config.retry {
            self.send_retry(hdr, local, remote)?;
            Err(Error::Done)
        } else {
            Ok(None)
        }
    }

    /// Create a server connection and add routes.
    fn create_server_conn(
        &mut self,
        hdr: &PacketHeader,
        token: Option<&AddressToken>,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<u64> {
        let odcid = match token {
            Some(token) => token.odcid.unwrap(),
            None => hdr.dcid,
        };
        let cid_len = self.cid_gen.cid_len();
        let scid = self.cid_gen.generate();
        let conn = Connection::new_server(&scid, local, remote, token, &self.config)?;
        let idx = self.conns.insert(conn);

        if cid_len > 0 {
            self.routes.insert_with_cid(scid, idx);
            self.routes.insert_with_cid(odcid, idx);
        } else {
            self.routes
                .insert_with_addr(FourTuple { local, remote }, idx);
        }

        Ok(idx)
    }

    /// Deliver the initial datagram (and buffered 0-RTT) to a connection.
    fn deliver_initial_to_conn(
        &mut self,
        idx: u64,
        hdr: &PacketHeader,
        buf: &mut [u8],
        info: &PacketInfo,
    ) -> Result<()> {
        // Pop buffered 0-RTT packets before borrowing conn, to avoid
        // double-mutable-borrow of self.
        let buffered = self.buffer.del(&hdr.dcid);

        if let Some(conn) = self.conns.get_mut(idx) {
            conn.set_index(idx);
            conn.set_queues(self.queues.clone());
            trace!(
                "{} create a server connection {:?}",
                &self.trace_id,
                conn.trace_id(),
            );

            self.handler.on_conn_created(conn);
            conn.mark_tickable(true);
            conn.recv(buf, info).map(|_| ())?;

            // Deliver buffered ZeroRTT packets
            if let Some(mut v) = buffered {
                trace!(
                    "{} try to delivery {} buffered zerortt packets to connection {:?}",
                    &self.trace_id,
                    v.len(),
                    conn.trace_id(),
                );
                for (ref mut pkt, pkt_info) in v.iter_mut() {
                    conn.recv(pkt, pkt_info).map(|_| ())?;
                }
            }
        }
        Ok(())
    }

    /// Decode and validate the address token.
    fn validate_address_token(
        &mut self,
        addr_token: &mut [u8],
        cli_addr: &SocketAddr,
        cli_pkt_dcid: &ConnectionId,
    ) -> Result<AddressToken> {
        let lifetime = self.config.address_token_lifetime;

        for key in &self.config.address_token_key {
            match AddressToken::decode(key, addr_token, cli_addr, cli_pkt_dcid, lifetime) {
                Ok(token) => return Ok(token),
                Err(Error::ExpiredToken) => return Err(Error::ExpiredToken),
                _ => continue, // try the next key
            }
        }
        Err(Error::InvalidToken)
    }

    /// Write a Version Negotiation packet which will be sent later.
    fn send_version_negotiation(
        &mut self,
        cli_pkt_hdr: &PacketHeader,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        let mut pkt_out = self.packets.get_buffer();
        let len =
            packet::version_negotiation(&cli_pkt_hdr.dcid, &cli_pkt_hdr.scid, &mut pkt_out[..])?;
        pkt_out.truncate(len);

        let pkt_info = PacketInfo {
            src: local,
            dst: remote,
            time: Instant::now(),
        };

        trace!(
            "{} send version negotiation: remote {:?} local {:?}",
            &self.trace_id,
            remote,
            local
        );
        self.packets.add_packet(pkt_out, pkt_info);
        Ok(())
    }

    /// Write a Retry packet which will be sent later.
    fn send_retry(
        &mut self,
        initial_pkt_hdr: &PacketHeader,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        let mut pkt_out = self.packets.get_buffer();

        // Generate a retry token
        let rscid = self.cid_gen.generate();
        let token = AddressToken::new_retry_token(remote, initial_pkt_hdr.dcid, rscid);
        let token = token.encode(&self.config.address_token_key[0])?;

        // Write a Retry packet
        let len = packet::retry(
            &rscid,                // server cid
            &initial_pkt_hdr.scid, // client cid
            &initial_pkt_hdr.dcid, // original dcid
            &token,
            crate::QUIC_VERSION_V1,
            &mut pkt_out[..],
        )?;
        pkt_out.truncate(len);

        let pkt_info = PacketInfo {
            src: local,
            dst: remote,
            time: Instant::now(),
        };

        trace!(
            "{} send retry: remote {:?} local {:?}",
            &self.trace_id,
            remote,
            local
        );
        self.packets.add_packet(pkt_out, pkt_info);
        Ok(())
    }

    /// Write a Stateless Reset packet which will be sent later.
    /// TODO: rate limit based on address
    fn send_stateless_reset(
        &mut self,
        pkt_in_len: usize,
        dcid: &ConnectionId,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        // Endpoints MUST discard packets that are too small to be valid QUIC
        // packets.
        if pkt_in_len < self.cid_gen.cid_len() + 19 {
            return Ok(());
        }

        let pkt_out_len = pkt_in_len - 1;
        if pkt_out_len < crate::MIN_RESET_PACKET_LEN {
            return Ok(());
        }
        let pkt_out_len = cmp::min(pkt_out_len, crate::MAX_RESET_PACKET_LEN);

        let key = &self.config.reset_token_key;
        let reset_token = ResetToken::generate(key, dcid);

        let mut pkt_out = self.packets.get_buffer();
        let len = packet::stateless_reset(pkt_out_len, &reset_token, &mut pkt_out[..])?;
        pkt_out.truncate(len);

        let pkt_info = PacketInfo {
            src: local,
            dst: remote,
            time: Instant::now(),
        };

        trace!(
            "{} send Stateless Reset {:?} token={:?} dcid_pkt_in={:?}",
            &self.trace_id,
            pkt_info,
            reset_token,
            dcid,
        );
        self.packets.add_packet(pkt_out, pkt_info);
        Ok(())
    }

    /// Return the amount of time until the next timeout event.
    pub fn timeout(&self) -> Option<Duration> {
        // There are still events pending
        let queues = self.queues.borrow();
        if !self.packets.is_empty() || !queues.is_empty() {
            return Some(crate::TIMER_GRANULARITY);
        }

        self.timers.time_remaining(Instant::now())
    }

    /// Process timeout events on the endpoint.
    pub fn on_timeout(&mut self, now: Instant) {
        while let Some(idx) = self.timers.next_expire(now) {
            if let Some(conn) = self.conns.get_mut(idx) {
                trace!(
                    "{} process timeout event, connection index {} trace id {}",
                    self.trace_id,
                    idx,
                    conn.trace_id(),
                );
                conn.mark_tickable(true);
                conn.on_timeout(now);
            }
        }
    }

    /// Process internal events of all tickable connections.
    pub fn process_connections(&mut self) -> Result<()> {
        trace!(
            "{} process {} tickable connections",
            &self.trace_id,
            self.conn_tickable_len()
        );
        let mut ready = Vec::<u64>::new();

        while let Some(idx) = self.conn_tickable_next() {
            if self.process_connection(idx, &mut ready) {
                continue;
            }
            self.cleanup_closed_conn(idx);
        }

        self.send_packets_out()?;

        // Add connection with internal events to the tickable queue again.
        for idx in ready {
            if let Some(conn) = self.conns.get_mut(idx) {
                conn.mark_tickable(true);
            }
        }

        Ok(())
    }

    /// Clean up a closed connection.
    fn cleanup_closed_conn(&mut self, idx: u64) {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return,
        };

        for stream_id in conn.stream_iter() {
            self.handler.on_stream_closed(conn, stream_id);
            conn.stream_destroy(stream_id);
        }

        self.handler.on_conn_closed(conn);
        conn.mark_tickable(false);
        conn.mark_sendable(false);
        self.timers.del(&idx);
        self.routes.remove(conn);
        self.conns.remove(idx);
    }

    /// Process internal events of a tickable connection.
    ///
    /// Return `true` if the connection has been processed successfully.
    /// Return `false` if the connection has been closed and need to be
    /// cleaned up.
    fn process_connection(&mut self, idx: u64, ready: &mut Vec<u64>) -> bool {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return true,
        };
        if conn.is_closed() {
            return false;
        }

        if !self.process_conn_events(idx) {
            return false;
        }
        if !self.process_conn_readable(idx) {
            return false;
        }
        if !self.process_conn_writable(idx) {
            return false;
        }

        self.finalize_conn_tick(idx, ready);
        true
    }

    /// Process endpoint-facing events on a connection.
    /// Returns false if connection closed.
    fn process_conn_events(&mut self, idx: u64) -> bool {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return true,
        };

        while let Some(event) = conn.poll() {
            match event {
                Event::ConnectionEstablished => self.handler.on_conn_established(conn),
                Event::NewToken(token) => self.handler.on_new_token(conn, token),
                Event::ScidToAdvertise(num) => {
                    let key = &self.config.reset_token_key;
                    Self::conn_add_scids(conn, num, &mut self.cid_gen, key, &mut self.routes);
                }
                Event::ScidRetired(cid) => self.routes.remove_with_cid(&cid),
                Event::DcidAdvertised(token) => self.routes.insert_with_token(token, idx),
                Event::DcidRetired(token) => self.routes.remove_with_token(&token),
                Event::ResetTokenAdvertised(token) => {
                    self.routes.insert_with_token(token, idx);
                }
                Event::StreamCreated(stream_id) => {
                    self.handler.on_stream_created(conn, stream_id);
                }
                Event::StreamClosed(stream_id) => {
                    self.handler.on_stream_closed(conn, stream_id);
                    conn.stream_destroy(stream_id);
                }
                Event::DatagramReceived => {
                    self.handler.on_dgram_readable(conn);
                }
            }
            if conn.is_closed() {
                return false;
            }
        }
        true
    }

    /// Process readable streams on a connection.
    /// Returns false if connection closed.
    fn process_conn_readable(&mut self, idx: u64) -> bool {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return true,
        };

        for stream_id in conn.stream_readable_iter() {
            if conn.stream_check_readable(stream_id) {
                self.handler.on_stream_readable(conn, stream_id);
                if conn.is_closed() {
                    return false;
                }
            }
        }
        true
    }

    /// Process writable streams on a connection.
    /// Returns false if connection closed.
    fn process_conn_writable(&mut self, idx: u64) -> bool {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return true,
        };

        for stream_id in conn.stream_writable_iter() {
            if conn.stream_check_writable(stream_id) {
                self.handler.on_stream_writable(conn, stream_id);
                if conn.is_closed() {
                    return false;
                }
            }
        }
        true
    }

    /// Finalize processing a connection tick: mark sendable, update timer.
    fn finalize_conn_tick(&mut self, idx: u64, ready: &mut Vec<u64>) {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return,
        };

        conn.mark_sendable(true);

        if let Some(t) = conn.timeout() {
            self.timers.add(idx, t, Instant::now());
        } else {
            self.timers.del(&idx);
        }

        if conn.is_ready() {
            trace!("conn {} is still ready", conn.trace_id());
            ready.push(idx);
        }
        conn.mark_tickable(false);
    }

    /// Add scids for the given connection
    fn conn_add_scids(
        conn: &mut Connection,
        num: u8,
        gen: &mut Box<dyn ConnectionIdGenerator>,
        token_key: &hmac::Key,
        routes: &mut ConnectionRoutes,
    ) {
        for i in 0..num {
            let (scid, reset_token) = gen.generate_cid_and_token(token_key);
            match conn.add_scid(scid, reset_token, true) {
                Ok(_) => (),
                Err(e) => {
                    warn!("add scid to {:?} : {:?}", conn.trace_id(), e);
                    break;
                }
            }

            let index = conn.index().unwrap();
            routes.insert_with_cid(scid, index);
        }
    }

    /// Check whether the given connection exists.
    pub(crate) fn conn_exist(&self, cid: ConnectionId) -> bool {
        self.routes.cid_table.contains_key(&cid)
    }

    /// Get the connection by index
    pub fn conn_get_mut(&mut self, index: u64) -> Option<&mut Connection> {
        match self.conns.get_mut(index) {
            Some(v) => Some(v),
            None => None,
        }
    }

    /// Return the index of a tickable connection
    fn conn_tickable_next(&mut self) -> Option<u64> {
        let queues = self.queues.borrow_mut();
        queues.tickable_next()
    }

    /// Return the number of tickable connections
    fn conn_tickable_len(&self) -> usize {
        let queues = self.queues.borrow();
        queues.tickable.len()
    }

    /// Return the index of a sendable connection
    fn conn_sendable_next(&mut self) -> Option<u64> {
        let queues = self.queues.borrow_mut();
        queues.sendable_next()
    }

    /// Return the number of sendble connections
    fn conn_sendable_len(&self) -> usize {
        let queues = self.queues.borrow();
        queues.sendable.len()
    }

    /// Send the QUIC packets out to the peer.
    fn send_packets_out(&mut self) -> Result<()> {
        trace!(
            "{} process {} sendable connections",
            &self.trace_id,
            self.conn_sendable_len()
        );
        let mut sent = FxHashSet::default();
        let mut total = 0;

        while self.conn_sendable_len() > 0 {
            while let Some(idx) = self.conn_sendable_next() {
                if !self.send_conn_packets(idx, &mut sent)? {
                    break;
                }

                if self.packets.has_full_batch() {
                    total += self.flush_batch()?;
                }
            }
        }

        self.update_sent_timers(&sent);
        total += self.flush_remaining()?;

        trace!("{} send total {} packets out", &self.trace_id, total);
        Ok(())
    }

    /// Generate packets for a single sendable connection.
    /// Returns Ok(true) to continue, Ok(false) to break.
    fn send_conn_packets(&mut self, idx: u64, sent: &mut FxHashSet<u64>) -> Result<bool> {
        if let Some(conn) = self.conns.get_mut(idx) {
            if conn.is_draining() || conn.is_closed() {
                conn.mark_sendable(false);
                return Ok(true);
            }

            let mut buf = self.packets.get_buffer();
            match conn.send(&mut buf) {
                Ok((len, info)) => {
                    buf.truncate(len);
                    self.packets.add_packet(buf, info);
                    sent.insert(idx);
                }
                Err(Error::Done) => {
                    self.packets.put_buffer(buf);
                    sent.insert(idx);
                    conn.mark_sendable(false);
                }
                Err(e) => {
                    self.packets.put_buffer(buf);
                    error!("{} generate packet err: {:?}", &self.trace_id, e);
                    return Err(e);
                }
            }
        }
        Ok(true)
    }

    /// Flush a full batch of packets to the sender.
    fn flush_batch(&mut self) -> Result<usize> {
        let batch = self.packets.next_batch();
        let done = match self.sender.on_packets_send(batch) {
            Ok(v) => v,
            Err(e) => {
                error!("{} send packet err: {:?}", &self.trace_id, e);
                return Err(e);
            }
        };
        self.packets.drain_front(done);
        Ok(done)
    }

    /// Update timers for connections that sent packets.
    fn update_sent_timers(&mut self, sent: &FxHashSet<u64>) {
        for idx in sent {
            if let Some(conn) = self.conns.get_mut(*idx) {
                if let Some(t) = conn.timeout() {
                    self.timers.add(*idx, t, Instant::now());
                } else {
                    self.timers.del(idx);
                }
            }
        }
    }

    /// Flush any remaining packets in the queue.
    fn flush_remaining(&mut self) -> Result<usize> {
        let mut total = 0;
        let mut batch = self.packets.next_batch();
        while !batch.is_empty() {
            trace!(
                "{} try to send remaining packets in packet queue",
                &self.trace_id,
            );

            let done = self.sender.on_packets_send(batch)?;
            if done == 0 {
                break;
            }
            total += done;
            self.packets.drain_front(done);
            batch = self.packets.next_batch();
        }
        Ok(total)
    }

    /// Gracefully or forcibly shutdown the endpoint.
    /// If `force` is false, cease creating new connections and wait for all
    /// active connections to close. Otherwise, forcibly close all the active
    /// connections.
    pub fn close(&mut self, force: bool) {
        self.closed = true;
        if !force {
            return;
        }

        trace!(
            "{} forcibly close {} connections",
            &self.trace_id,
            self.conns.len()
        );
        for (_, conn) in self.conns.conns.iter_mut() {
            for stream_id in conn.stream_iter() {
                self.handler.on_stream_closed(conn, stream_id);
                conn.stream_destroy(stream_id);
            }
            self.handler.on_conn_closed(conn);
        }
        self.timers.clear();
        self.routes.clear();
        self.conns.clear();
    }

    /// Set the connection id generator
    /// By default, the RandomConnectionIdGenerator is used.
    pub fn set_cid_generator(&mut self, cid_gen: Box<dyn ConnectionIdGenerator>) {
        self.cid_gen = cid_gen;
    }

    /// Set the unique trace id for the endpoint
    pub fn set_trace_id(&mut self, trace_id: String) {
        self.trace_id = trace_id
    }

    /// Return the unique trace id for the endpoint
    pub fn trace_id(&self) -> &str {
        &self.trace_id
    }
}
